apiVersion: v2
appVersion: "1.0"
description: A Helm chart for j-j App
name: j-j
home: https://github.com/hmcts/j-j
version: 0.0.1
maintainers:
  - name: HMCTS j team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
